name: MinigamePlugin
version: '5.0.0'
main: base.MinigamePlugin
api-version: '1.21'
commands:
  misc:
    description: Miscellaneous commands
    usage: /<command> <name> <...>
  minigame:
    description: Shows the minigame menu
    usage: /<command> <name>
  mg_disco_mayhem:
    description: Starts the Disco Mayhem minigame
    usage: /<command> <state>
  mg_blueprint_bazaar:
    description: Starts the Blueprint Bazaar minigame
    usage: /<command> <state>
  mg_hole_in_the_wall:
    description: Starts the Hole In The Wall minigame
    usage: /<command> <state>
  mg_maze_hunt:
    description: Starts the Maze Hunt minigame
    usage: /<command> <state>
  mg_parkour_dash:
    description: Starts the Parkour Dash minigame
    usage: /<command> <state>